version: "2"
services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    volumes:
      - "./policies:/policies"
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      - "--watch"
      - "/policies"
